export const INITIAL_REQUEST_START = 'INITIAL_REQUEST_START';
export const INITIAL_REQUEST_FAIL = 'INITIAL_REQUEST_FAIL';
export const INITIAL_REQUEST_SUCCESS = 'INITIAL_REQUEST_SUCCESS';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_ALL_USERS_START = 'FETCH_ALL_USERS_START';
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';