export const GET_PAGES_START = 'GET_PAGES_START';
export const GET_PAGES_FAIL = 'GET_PAGES_FAIL';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_ALL_USERS_START = 'FETCH_ALL_USERS_START';
export const FETCH_ALL_USERS_FAIL = 'FETCH_ALL_USERS_FAIL';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';